### ISSUE TITLE
Kubernetes integration not disabling other inputs

### ISSUE THREAD

**Issue by mholttech** [andrewkroh/terraform-module-fleet#12]
I'm trying to use the Kubernetes integration and it's only disabling the data streams in the same input and not disabling the other inputs.

For example when I deploy kubernetes.kube-state-metrics.state_replicaset.kubernetes_metrics only the Kubernetes Replicaset metrics data stream is enabled for Kube State Metrics but all of the other inputs & their data streams are still enabled. See the screenshot below.

![image](https://github.com/andrewkroh/terraform-module-fleet/assets/6945933/eba2e3d6-c0ff-4f89-ac5d-5e14bc4ff0a0)

**Comment by andrewkroh** [comment]
I thought I had fixed that with 68117a6390609538a0ff6dc96b45166d88706ec2. Are you running the latest commit?

**Comment by mholttech** [comment]
Yea, I ditched my local fork last week and built the binary from the latest code you released

**Comment by andrewkroh** [comment]
I think I see the issue. It may also need to disable every unused package_policy too. I was operating under the assumption that if the request did not include anything for those unused package policies that they would be treated as `enabled: false`. Here's the request from Kibana.

<img width="660" alt="Screenshot 2023-08-30 at 19 00 37" src="https://github.com/andrewkroh/terraform-module-fleet/assets/4565752/08a8144f-ae2b-4ca6-96dc-0f3e7fe961cf">

So I probably need to modify the `fleet_package_policy` TF module to insert an entry into `inputs` for each of those unused package_policy+input_type combos.

**Comment by mholttech** [comment]
That's kind of annoying... Too bad all inputs are disabled by default as that would make life easier in many ways.

**Comment by andrewkroh** [comment]
I have an untested fix if you would like to try this: 6a59ab08c2158bb9562bde651a142c633a484be6

**Comment by mholttech** [comment]
Sure, i'll grab it and report back shortly

**Comment by mholttech** [comment]
Looks like that did the trick.

![image](https://github.com/andrewkroh/terraform-module-fleet/assets/6945933/90b3c021-3dfd-4281-af66-bf6bc52a6b3d)

**Comment by mholttech** [comment]
I just updated all of the kubernetes integration policies I was adding to this fleet agent policy and they all look good now

**Comment by andrewkroh** [comment]
Sweet. I'll clean this fix up and open a PR. Thanks for testing.
