### ISSUE TITLE
field type not found in type fleetpkg.Owner

### ISSUE THREAD

**Issue by mholttech** [andrewkroh/terraform-module-fleet#15]
I'm seeing this error when using the generator on my machine. I also see it in the github actions output.

https://github.com/andrewkroh/terraform-module-fleet/actions/runs/6293534967/job/17084177136#step:7:23

**Comment by mholttech** [comment]
Looking at this further, any packages that have the new Owner field are not processing at all

**Comment by andrewkroh** [comment]
I should probably change something in to code so that it returns a non-zero exit code. Then at least I will get a notification about the GH action failing.

But updating to the latest go-fleetpkg should fix it. See #16.

**Comment by mholttech** [comment]
That does the trick, thanks!

**Comment by andrewkroh** [comment]
Add #20 to fail fast and set an exit code.
