### ISSUE TITLE
Support for Input packages

### ISSUE THREAD

**Issue by mholttech** [andrewkroh/terraform-module-fleet#2]
I'm trying to use the generator on some input packages but it seems like there is an issue processing them due to the different directory structure for input pacakges. Have you looked into this yet? Specifically i'm trying to use the "log" and "sql_input" packages.

````
 ./fleet-terraform-generator generate batch --packages-dir integrations/packages --out out "log/logs/logfile"
integrations/packages / log / logs /  / logfile / out
Error: error generating module for log/logs/logfile: input "logfile" was not found within policy template "logs"

 ./fleet-terraform-generator generate batch --packages-dir integrations/packages --out out "sql/sql/sql_metrics"
integrations/packages / sql / sql /  / sql/metrics / out
Error: error generating module for sql/sql/sql_metrics: open integrations/packages/sql/manifest.yml: no such file or directory
````

**Comment by andrewkroh** [comment]
I was aware that there are issues with input packages.

What I would recommend in that case is to manually construct the package_policy request. The way I would approach this is to let Fleet show you the request it makes, and then use that to either directly compose a Mastercard/restapi resource or use that to guide you in using https://github.com/andrewkroh/terraform-module-fleet/tree/main/fleet_package_policy.

<img width="1326" alt="Screenshot 2023-06-09 at 12 03 26" src="https://github.com/andrewkroh/terraform-module-fleet/assets/4565752/710a5a07-8199-4234-9314-7602533311bb">

<img width="655" alt="Screenshot 2023-06-09 at 12 03 44" src="https://github.com/andrewkroh/terraform-module-fleet/assets/4565752/0872a51b-242e-4c14-8b8d-01c718bd60bf">

**Comment by mholttech** [comment]
thanks for the quick feedback!

**Comment by mholttech** [comment]
Awesome! I'll give it a try and let you know if I see any issues
