### ISSUE TITLE
Dots in Fleet variable names cause issues in Terraform

### ISSUE THREAD

**Issue by mholttech** [andrewkroh/terraform-module-fleet#3]
I've found a few issues with the input packages

Inputs can generate an invalid terraform variable when the manifest file defines a dot separated fields such as "data_stream.dataset". 
https://github.com/elastic/integrations/blob/e234ffb8ad8dd70cc73a216cc2ed329620485077/packages/log/manifest.yml#L27

I was able to resolve this by inserting this after line 258 of [fleet-terraform-generator/internal/module/generate.go](https://github.com/andrewkroh/terraform-module-fleet/blob/main/fleet-terraform-generator/internal/module/generate.go)

````
	// Replace any periods with underscore so that a valid TF variable is generated.
	if strings.Contains(name, ".") {
		name = strings.ReplaceAll(name, ".", "_")
	}
````
---

Inputs with dot separated fields such as "data_stream.dataset" as the JSON key causes terraform to fail.

https://github.com/andrewkroh/terraform-module-fleet/blob/ffa10318d2e4dd57010233ac0e2f1b6f84ceac92/fleet_integrations/log_logs_logfile/module.tf.json#L54

Terraform generates the following error:

````
│ Error: Reference to undeclared resource
│
│   on ../../fleet-terraform-generator/out/log_logs_logfile/module.tf.json line 56, in module.fleet_package_policy:
│   56:       "data_stream_variables_json": "${jsonencode({\n  custom = var.custom_yaml\n  data_stream.dataset = var.data_stream_dataset\n  paths = var.paths\n  processors = var.processors_yaml\n  tags = var.tags\n})}",
│
│ A managed resource "data_stream" "dataset" has not been declared in module.integration_log_logs.
````

Wrapping this in quotes prevents this error but I haven't been able to figure out how to update the code to do this.

---

I know there's nothing you can do for this one but for the SQL Metrics it looks like there is an issue with the integrations manifest.yml causing the generator to fail to create the variable for data_stream.dataset.

**Comment by andrewkroh** [comment]
I pushed two changes:

- b0b04bdd75a990ef749986573e1e2570b6fef882 Quote variable names containing dots in expressions

- cb99e50177e627673164fb2201e9557e23a3e6c3 Replace dots with underscores in TF module variables

**Comment by andrewkroh** [comment]
> I know there's nothing you can do for this one but for the SQL Metrics it looks like there is an issue with the integrations manifest.yml causing the generator to fail to create the variable for data_stream.dataset.

Yeah, that looks like a bug in that the manifest.yml does not contain a `data_stream.dataset` variable. Whereas other input packages do declare the variable. The package even tries to use the variable at https://github.com/elastic/integrations/blob/b723d42a8282f5e00caa865ff020932da21d511f/packages/sql_input/agent/input/input.yml.hbs#L11.

**Comment by andrewkroh** [comment]
Created an issue at https://github.com/elastic/integrations/issues/6529
