### ISSUE TITLE
Generator doesn't identify the elastic_agent integration

### ISSUE THREAD

**Issue by mholttech** [andrewkroh/terraform-module-fleet#5]
I've noticed that the generator isn't identifying the [elastic_agent](https://github.com/elastic/integrations/tree/main/packages/elastic_agent) package and I can't figure out why.

````
fleet-terraform-generator list --packages-dir ~/integrations/packages | grep elastic
elastic_package_registry/elastic_package_registry/metrics/prometheus_metrics
elasticsearch/elasticsearch/audit/logfile
elasticsearch/elasticsearch/ccr/elasticsearch_metrics
elasticsearch/elasticsearch/cluster_stats/elasticsearch_metrics
elasticsearch/elasticsearch/deprecation/logfile
elasticsearch/elasticsearch/enrich/elasticsearch_metrics
elasticsearch/elasticsearch/gc/logfile
elasticsearch/elasticsearch/index/elasticsearch_metrics
elasticsearch/elasticsearch/index_recovery/elasticsearch_metrics
elasticsearch/elasticsearch/index_summary/elasticsearch_metrics
elasticsearch/elasticsearch/ingest_pipeline/elasticsearch_metrics
elasticsearch/elasticsearch/ml_job/elasticsearch_metrics
elasticsearch/elasticsearch/node/elasticsearch_metrics
elasticsearch/elasticsearch/node_stats/elasticsearch_metrics
elasticsearch/elasticsearch/pending_tasks/elasticsearch_metrics
elasticsearch/elasticsearch/server/logfile
elasticsearch/elasticsearch/shard/elasticsearch_metrics
elasticsearch/elasticsearch/slowlog/logfile
````

**Comment by andrewkroh** [comment]
That package doesn't have any package polices that could be added to an Agent policy. That is there are no policy_templates in the manifest.yml.

That package can be installed, but it cannot be added to an Agent policy. So to install this package I would directly use the `POST /epm/packages/{pkgName}/{pkgVersion}`[^1] API in Fleet. For other packages installation happens automatically as a side effect of creating a package policy that references the package.

[^1]: https://github.com/elastic/kibana/blob/44bfd0c343ab0d1174bf948b40cab62f12acc477/x-pack/plugins/fleet/common/openapi/bundled.yaml#L649-L701

**Comment by mholttech** [comment]
Thanks Andrew! We've been adding this to an Agent policy in the Fleet UI but looking closer at the README it is enabled/disabled with the Agent Monitoring settings for the Agent policy, so we never needed to.

**Comment by andrewkroh** [comment]
There are a few packages that are similar such as `ti_util` that it would be useful to have a way to install from the Terraform module even if they are not part of an Agent policy. I might raise an issue for this in elastic/terraform-provider-elasticstack.
